# Generated by Django 5.0.3 on 2024-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_categoria_alter_juego_imagen_alter_juego_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
