# Generated by Django 5.0.3 on 2024-03-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='id',
        ),
        migrations.AddField(
            model_name='juego',
            name='juego_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
